### PR TITLE
Added reason support and languageIds tag

### PR DESCRIPTION
**Pull request by danibram**
Added support for `.re` and `.rei` files

### CODE REVIEW

**Comment by danibram** [comment]
Sorry I commited also the support for the languageIds tags, to support not only icons by filename and extension. I addded an example of my problem... I tried to follow your icon schema but you can review the changes, there are a lot of cases =)

Screenshot 2021-02-05 at 07 11 48

**Comment by artlaman** [comment]
Hey @danibram. Thanks for your contribution. 🙂
Well. The `lambda` icon was added just for fun specifically for Haskell. It's just sort of an inside joke, and I don't have plans to use it for other ML languages. Don't you mind using `code` icon for `.re` and `.rei` file extensions?

Speaking of `languageIds` I intentionally don't use it. Firstly, VS Code documentation does not contain a table of correspondence between `language identifiers` and `file extensions`.  And this list is short and might change over time. Also, users might have and might not have VSCode extensions that define new language identifiers and file extensions associated with them. Indeed, Looks messy to me. Indeed, using `languageIds` has its advantages, like automatically changing icons when the user changes the language of a current file with `⌘ K M` hotkey. But I didn't really like the prospect of maintaining three lists (`languageIds`, `fileExtensions`, and `fileNames`).

But it looks like the `docker` will have to be left on the `languageIds` list since wildcards are not supported. I thought that by convention when you have multiple dockerfiles, you have to place them in different directories. But it appears there are no conventions. 😄

**Comment by artlaman** [comment]
Also, it might be better to just add `.yml` and `.yaml` file extensions to `fileExtensions` list instead of adding `docker-compose.yml` to `fileNames` list.

**Comment by danibram** [comment]
Ok, I modified the PR as discussed here.
thanks

**Comment by artlaman** [comment]
Great! 👍 Thanks again for your contribution
I'll publish a new version as soon as I can.

**Pull request merged**
